name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
      id: go

    - name: Checkout uhppote-core
      run: git clone https://github.com/uhppoted/uhppote-core.git ../uhppote-core
  
    - name: Checkout uhppoted-lib
      run: git clone https://github.com/uhppoted/uhppoted-lib.git ../uhppoted-lib

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build-all
