name: nightly

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22
      id: go

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: make build-all

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/linux/uhppote-cli
        name: uhppote-cli_linux-nightly

    - name: Upload MacOS Intel artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/darwin-x64/uhppote-cli
        name: uhppote-cli_darwin-x64-nightly

    - name: Upload MacOS Apple silicon artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/darwin-arm64/uhppote-cli
        name: uhppote-cli_darwin-arm64-nightly

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/windows/uhppote-cli
        name: uhppote-cli_windows-nightly

    - name: Upload ARM artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/arm/uhppote-cli
        name: uhppote-cli_arm-nightly

    - name: Upload ARM7 artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/arm7/uhppote-cli
        name: uhppote-cli_arm7-nightly
